apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    volumeMounts: 
    - name: logs
      mountPath: /var/log/nginx
  volumes:
  - name: logs
    persistentVolumeClaim: 
      claimName: claim-log-1
