apiVersion: v1
kind: Pod
metadata:
  name: three-cont-pod
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}

  containers:
    - name: container-1
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - echo "Hello from container 1" >> /shared-data/output.txt;
          sleep 3600;
      volumeMounts:
        - name: shared-volume
          mountPath: /shared-data

    - name: container-2
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - echo "Hello from container 2" >> /shared-data/output.txt;
          sleep 3600;
      volumeMounts:
        - name: shared-volume
          mountPath: /shared-data

    - name: container-3
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - cat /shared-data/output.txt;
          sleep 3600;
      volumeMounts:
        - name: shared-volume
          mountPath: /shared-data